version: '3.8'

services:
  linguagun:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linguagun_app
    ports:
      - "5100:5100"
    restart: always
    environment:
      - PORT=5100
      - PYTHONUNBUFFERED=1
