/**
 * Preset lessons for multi-language listening and dictation practice.
 * 100% verified real YouTube videos with verified transcripts and embed support.
 */

export const PRESET_LANGUAGES = [
  {
    id: "en",
    name: "Tiếng Anh",
    flag: "🇺🇸",
    hasSubcategories: true,
    subcategories: [
      { id: "en_general", name: "Giao tiếp & Đời sống", icon: "💬", tag: "A1–C1" },
      { id: "en_toeic", name: "Luyện thi TOEIC", icon: "🎯", tag: "Part 1–4 & 800+" },
      { id: "en_ielts", name: "Luyện thi IELTS", icon: "🎓", tag: "Band 5.0–8.0+" },
    ],
  },
  {
    id: "zh",
    name: "Tiếng Trung (中文)",
    flag: "🇨🇳",
    hasSubcategories: false,
    defaultCategory: "zh",
  },
  {
    id: "ja",
    name: "Tiếng Nhật (日本語)",
    flag: "🇯🇵",
    hasSubcategories: false,
    defaultCategory: "ja",
  },
  {
    id: "ko",
    name: "Tiếng Hàn (한국어)",
    flag: "🇰🇷",
    hasSubcategories: false,
    defaultCategory: "ko",
  },
];

export const PRESET_LESSONS_BY_CATEGORY = {
  en_general: {
    name: "Giao tiếp & Đời sống",
    icon: "💬",
    desc: "Lộ trình 5 cấp độ từ căn bản A1 đến diễn thuyết truyền cảm hứng C1",
    lessons: [
      {
        level: 1,
        levelNumber: 1,
        badge: "A1 • Sơ cấp",
        difficulty: "Rất dễ",
        diffColor: "#10b981", // Emerald green
        id: "RP1AL2DU6vQ",
        url: "https://www.youtube.com/watch?v=RP1AL2DU6vQ",
        title: "English Daily Routine – Thói quen hàng ngày A1",
        author: "English Easy Practice",
        duration: "1:49",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Từ vựng thói quen hàng ngày, phát âm cực chậm và rõ ràng cho người mới bắt đầu.",
      },
      {
        level: 2,
        levelNumber: 2,
        badge: "A2 • Cơ bản",
        difficulty: "Dễ",
        diffColor: "#06b6d4", // Cyan
        id: "bgfdqVmVjfk",
        url: "https://www.youtube.com/watch?v=bgfdqVmVjfk",
        title: "At the Restaurant Conversation – Gọi món tại nhà hàng",
        author: "English Speaking Success",
        duration: "4:49",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Tình huống giao tiếp thực tế khi gọi món, hỏi giá và thanh toán.",
      },
      {
        level: 3,
        levelNumber: 3,
        badge: "B1 • Trung cấp",
        difficulty: "Trung bình",
        diffColor: "#f59e0b", // Amber
        id: "9AVwbe4e6tI",
        url: "https://www.youtube.com/watch?v=9AVwbe4e6tI",
        title: "Yunjin (LE SSERAFIM) – Phỏng vấn truyền cảm hứng",
        author: "Variety Up Next",
        duration: "4:32",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Phỏng vấn tự nhiên về hành trình nghệ thuật, tốc độ nói vừa phải, giàu cảm xúc.",
      },
      {
        level: 4,
        levelNumber: 4,
        badge: "B2 • Nâng cao",
        difficulty: "Khá khó",
        diffColor: "#f97316", // Orange
        id: "h6fcK_fRYaI",
        url: "https://www.youtube.com/watch?v=h6fcK_fRYaI",
        title: "The Egg – Triết lý cuộc sống (A Short Story)",
        author: "Kurzgesagt",
        duration: "7:57",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Câu chuyện triết học kinh điển của Kurzgesagt, giọng đọc chuẩn Anh-Mỹ truyền cảm.",
      },
      {
        level: 5,
        levelNumber: 5,
        badge: "C1 • Thử thách",
        difficulty: "Khó",
        diffColor: "#ef4444", // Red
        id: "UF8uR6Z6KLc",
        url: "https://www.youtube.com/watch?v=UF8uR6Z6KLc",
        title: "Steve Jobs Stanford Speech – Bài phát biểu lịch sử",
        author: "Stanford University",
        duration: "15:04",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Bài diễn thuyết tốt nghiệp kinh điển tại ĐH Stanford: Hãy cứ khát khao, hãy cứ dại khờ.",
      },
    ],
  },
  en_toeic: {
    name: "Luyện thi TOEIC",
    icon: "🎯",
    desc: "Trọng tâm kỹ năng Nghe từ Part 1 đến Part 4 & đề 800+",
    lessons: [
      {
        level: 1,
        levelNumber: 1,
        badge: "Part 1 • Tranh ảnh",
        difficulty: "Rất dễ",
        diffColor: "#10b981",
        id: "SaV2m8jtaRI",
        url: "https://www.youtube.com/watch?v=SaV2m8jtaRI",
        title: "TOEIC Part 1: Photographs Practice & Bí quyết nghe tranh",
        author: "E2 TOEIC",
        duration: "5:00",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Rèn phản xạ nhận diện hành động và vị trí đồ vật trong tranh ảnh Part 1.",
      },
      {
        level: 2,
        levelNumber: 2,
        badge: "Part 2 • Hỏi & Đáp",
        difficulty: "Dễ",
        diffColor: "#06b6d4",
        id: "ZWFDAnY9v04",
        url: "https://www.youtube.com/watch?v=ZWFDAnY9v04",
        title: "TOEIC Part 2: Question & Response – Phản xạ tức thì",
        author: "TOEIC Listening Hub",
        duration: "9:03",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Bộ câu hỏi Wh-questions và Yes/No với các bẫy phát âm đồng âm phổ biến.",
      },
      {
        level: 3,
        levelNumber: 3,
        badge: "Part 3 • Hội thoại",
        difficulty: "Trung bình",
        diffColor: "#f59e0b",
        id: "vUs0AbOfpfw",
        url: "https://www.youtube.com/watch?v=vUs0AbOfpfw",
        title: "TOEIC Part 3: Short Conversations – Tình huống công sở",
        author: "English Listening Academy",
        duration: "7:54",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Hội thoại 2-3 người về văn phòng, lịch họp, đặt vé và giao nhận hàng hóa.",
      },
      {
        level: 4,
        levelNumber: 4,
        badge: "Part 4 • Độc thoại",
        difficulty: "Khá khó",
        diffColor: "#f97316",
        id: "G-FYo1OcfQw",
        url: "https://www.youtube.com/watch?v=G-FYo1OcfQw",
        title: "TOEIC Part 4: Short Talks – Thông báo & Hội thảo",
        author: "Practice TOEIC Test",
        duration: "5:53",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Bài nói một người: thông báo chuyến bay, tin nhắn thoại và bản tin nội bộ.",
      },
      {
        level: 5,
        levelNumber: 5,
        badge: "Target 800+ • Nâng cao",
        difficulty: "Khó",
        diffColor: "#ef4444",
        id: "6HHfz6ZQJ-8",
        url: "https://www.youtube.com/watch?v=6HHfz6ZQJ-8",
        title: "TOEIC Master: Break 800 Points – Tốc độ thực chiến",
        author: "TOEIC Master Club",
        duration: "3:57",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Đoạn nghe tốc độ nhanh, nhiều nối âm và từ vựng thương mại quốc tế 800+.",
      },
    ],
  },
  en_ielts: {
    name: "Luyện thi IELTS",
    icon: "🎓",
    desc: "Từ Form Completion Section 1 đến Lecture Section 4 & Band 8.0+",
    lessons: [
      {
        level: 1,
        levelNumber: 1,
        badge: "Section 1 • Form Filling",
        difficulty: "Rất dễ",
        diffColor: "#10b981",
        id: "0-nmMAw-FMs",
        url: "https://www.youtube.com/watch?v=0-nmMAw-FMs",
        title: "IELTS Section 1: Form Completion – Nghe điền thông tin",
        author: "IELTS Listening Practice",
        duration: "2:50",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Luyện nghe bắt số điện thoại, tên riêng, ngày tháng và địa chỉ chính xác 100%.",
      },
      {
        level: 2,
        levelNumber: 2,
        badge: "Section 2 • Đời sống",
        difficulty: "Dễ",
        diffColor: "#06b6d4",
        id: "C9LkYETkhg0",
        url: "https://www.youtube.com/watch?v=C9LkYETkhg0",
        title: "IELTS Section 2: Monologue Guide – Hướng dẫn nơi làm việc",
        author: "IELTS Listening Pro",
        duration: "6:49",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Một người thuyết minh về quy định làm việc, sơ đồ văn phòng và tiện ích công cộng.",
      },
      {
        level: 3,
        levelNumber: 3,
        badge: "Section 3 • Thảo luận nhóm",
        difficulty: "Trung bình",
        diffColor: "#f59e0b",
        id: "VExCSkDBHDA",
        url: "https://www.youtube.com/watch?v=VExCSkDBHDA",
        title: "IELTS Section 3: Academic Techniques & Thảo luận nghiên cứu",
        author: "IELTS Advantage",
        duration: "4:32",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Thảo luận giữa sinh viên và giảng viên về đề tài nghiên cứu và phương pháp luận.",
      },
      {
        level: 4,
        levelNumber: 4,
        badge: "Section 4 • Giảng đường",
        difficulty: "Khá khó",
        diffColor: "#f97316",
        id: "EPgHrKRZniE",
        url: "https://www.youtube.com/watch?v=EPgHrKRZniE",
        title: "IELTS Section 4: Academic Lecture – Bài giảng chuyên đề",
        author: "Fastrack IELTS",
        duration: "5:22",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Bài giảng học thuật đại học về môi trường, lịch sử và tâm lý học hành vi.",
      },
      {
        level: 5,
        levelNumber: 5,
        badge: "Band 8.0+ • Trí tuệ",
        difficulty: "Khó",
        diffColor: "#ef4444",
        id: "9uZ-jeZS8d0",
        url: "https://www.youtube.com/watch?v=9uZ-jeZS8d0",
        title: "Can You Solve the Jail Break Riddle? – Câu đố logic tư duy",
        author: "TED-Ed",
        duration: "3:25",
        sourceLang: "en",
        targetLang: "vi",
        langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
        summary: "Câu đố logic toán học cực cuốn từ TED-Ed, luyện tư duy phản biện ngôn ngữ học thuật.",
      },
    ],
  },
  zh: {
    name: "Tiếng Trung (中文)",
    icon: "🇨🇳",
    desc: "Lộ trình 5 cấp độ từ HSK 1 đến HSK 6 & Phỏng vấn đường phố",
    lessons: [
      {
        level: 1,
        levelNumber: 1,
        badge: "HSK 1-2 • Sơ cấp",
        difficulty: "Rất dễ",
        diffColor: "#10b981",
        id: "MYQrQvbR8Vk",
        url: "https://www.youtube.com/watch?v=MYQrQvbR8Vk",
        title: "我的⼀天 My Daily Routine – Một ngày của tôi (HSK 1–2)",
        author: "Everyday Chinese",
        duration: "9:07",
        sourceLang: "zh",
        targetLang: "vi",
        langLabel: "🇨🇳 中文 → 🇻🇳 Tiếng Việt",
        summary: "Từ vựng sinh hoạt hàng ngày, câu ngắn dễ nhớ và phát âm Bắc Kinh chuẩn mực.",
      },
      {
        level: 2,
        levelNumber: 2,
        badge: "HSK 2-3 • Cơ bản",
        difficulty: "Dễ",
        diffColor: "#06b6d4",
        id: "GbDCWkTeOgA",
        url: "https://www.youtube.com/watch?v=GbDCWkTeOgA",
        title: "忘带钱了 – Quên mang tiền (Truyện cười慢速中文)",
        author: "Slow Chinese Stories",
        duration: "5:22",
        sourceLang: "zh",
        targetLang: "vi",
        langLabel: "🇨🇳 中文 → 🇻🇳 Tiếng Việt",
        summary: "Mẩu chuyện hài hước bằng tiếng Trung đọc chậm, kèm phụ đề song ngữ Việt-Trung.",
      },
      {
        level: 3,
        levelNumber: 3,
        badge: "HSK 4 • Trung cấp",
        difficulty: "Trung bình",
        diffColor: "#f59e0b",
        id: "ot08DY_ns88",
        url: "https://www.youtube.com/watch?v=ot08DY_ns88",
        title: "找工作 Looking for a job – Phỏng vấn việc làm",
        author: "Mandarin Chinese Podcast",
        duration: "3:40",
        sourceLang: "zh",
        targetLang: "vi",
        langLabel: "🇨🇳 中文 → 🇻🇳 Tiếng Việt",
        summary: "Tình huống trao đổi công việc, kinh nghiệm làm việc và đãi ngộ trong doanh nghiệp.",
      },
      {
        level: 4,
        levelNumber: 4,
        badge: "HSK 5 • Thực tế",
        difficulty: "Khá khó",
        diffColor: "#f97316",
        id: "97NV2txklwk",
        url: "https://www.youtube.com/watch?v=97NV2txklwk",
        title: "Streettalk Ep. 4 – Phỏng vấn đường phố Trung Quốc",
        author: "Better in Chinese",
        duration: "4:47",
        sourceLang: "zh",
        targetLang: "vi",
        langLabel: "🇨🇳 中文 → 🇻🇳 Tiếng Việt",
        summary: "Tiếng lóng, cách diễn đạt tự nhiên của giới trẻ Trung Quốc ngoài đời thực.",
      },
      {
        level: 5,
        levelNumber: 5,
        badge: "HSK 6 • Diễn thuyết",
        difficulty: "Khó",
        diffColor: "#ef4444",
        id: "j_t0XlFoCjU",
        url: "https://www.youtube.com/watch?v=j_t0XlFoCjU",
        title: "向你的困境借東西 – Mượn sức từ nghịch cảnh (TEDx)",
        author: "TEDxTaipei",
        duration: "8:51",
        sourceLang: "zh",
        targetLang: "vi",
        langLabel: "🇨🇳 中文 → 🇻🇳 Tiếng Việt",
        summary: "Bài diễn thuyết truyền động lực sâu sắc của Logan Hsu tại TEDxTaipei.",
      },
    ],
  },
  ja: {
    name: "Tiếng Nhật (日本語)",
    icon: "🇯🇵",
    desc: "Lộ trình 5 cấp độ từ JLPT N5 đến N1 & Phỏng vấn công sở Nhật Bản",
    lessons: [
      {
        level: 1,
        levelNumber: 1,
        badge: "JLPT N5 • Sơ cấp",
        difficulty: "Rất dễ",
        diffColor: "#10b981",
        id: "jMW-PK281kE",
        url: "https://www.youtube.com/watch?v=jMW-PK281kE",
        title: "Japanese Practice for Beginners – JLPT N5 Slow & Easy",
        author: "Akiko Japanese Conversations",
        duration: "8:09",
        sourceLang: "ja",
        targetLang: "vi",
        langLabel: "🇯🇵 日本語 → 🇻🇳 Tiếng Việt",
        summary: "Nghe hiểu tiếng Nhật N5 phát âm chậm, rõ ràng, câu thoại cơ bản cho người mới bắt đầu.",
      },
      {
        level: 2,
        levelNumber: 2,
        badge: "JLPT N4 • Cơ bản",
        difficulty: "Dễ",
        diffColor: "#06b6d4",
        id: "u9BHVq8opDI",
        url: "https://www.youtube.com/watch?v=u9BHVq8opDI",
        title: "Normal Day in My Life – Một ngày bình thường ở Nhật (N4)",
        author: "Akane Japanese Class",
        duration: "9:44",
        sourceLang: "ja",
        targetLang: "vi",
        langLabel: "🇯🇵 日本語 → 🇻🇳 Tiếng Việt",
        summary: "Vlog đời thường đi siêu thị, nấu ăn và dọn dẹp nhà cửa bằng tiếng Nhật đời sống.",
      },
      {
        level: 3,
        levelNumber: 3,
        badge: "JLPT N3 • Trung cấp",
        difficulty: "Trung bình",
        diffColor: "#f59e0b",
        id: "_Z7j3PEU358",
        url: "https://www.youtube.com/watch?v=_Z7j3PEU358",
        title: "We're Dreaming in TOKYO – Giấc mơ Tokyo",
        author: "Tokyo Metropolitan Gov",
        duration: "4:11",
        sourceLang: "ja",
        targetLang: "vi",
        langLabel: "🇯🇵 日本語 → 🇻🇳 Tiếng Việt",
        summary: "Video giới thiệu công việc và cuộc sống tại thủ đô Tokyo do chính quyền Tokyo sản xuất.",
      },
      {
        level: 4,
        levelNumber: 4,
        badge: "JLPT N2 • Công sở",
        difficulty: "Khá khó",
        diffColor: "#f97316",
        id: "Hc5sO1HjuXU",
        url: "https://www.youtube.com/watch?v=Hc5sO1HjuXU",
        title: "Tips for Japanese Job Interview – Phỏng vấn xin việc",
        author: "TCJ Tokyo",
        duration: "8:32",
        sourceLang: "ja",
        targetLang: "vi",
        langLabel: "🇯🇵 日本語 → 🇻🇳 Tiếng Việt",
        summary: "Kính ngữ (Keigo) và phong thái ứng xử chuẩn mực khi phỏng vấn vào công ty Nhật Bản.",
      },
      {
        level: 5,
        levelNumber: 5,
        badge: "JLPT N1 • Diễn thuyết",
        difficulty: "Khó",
        diffColor: "#ef4444",
        id: "0nNCXFT_Ots",
        url: "https://www.youtube.com/watch?v=0nNCXFT_Ots",
        title: "Meet a 12-Year-Old Patent Holder – Thần đồng sáng chế",
        author: "TEDx Talks",
        duration: "7:57",
        sourceLang: "ja",
        targetLang: "vi",
        langLabel: "🇯🇵 日本語 → 🇻🇳 Tiếng Việt",
        summary: "Bài thuyết trình đầy cảm hứng của cô bé Asuka Kamiya tại sân khấu TEDx Kyoto.",
      },
    ],
  },
  ko: {
    name: "Tiếng Hàn (한국어)",
    icon: "🇰🇷",
    desc: "Lộ trình 5 cấp độ từ TOPIK 1 đến TOPIK 6 & Văn hóa Hàn Quốc",
    lessons: [
      {
        level: 1,
        levelNumber: 1,
        badge: "TOPIK 1 • Sơ cấp",
        difficulty: "Rất dễ",
        diffColor: "#10b981",
        id: "cWcbK176lQs",
        url: "https://www.youtube.com/watch?v=cWcbK176lQs",
        title: "Fun & Short Story – Câu chuyện vui cho người mới học",
        author: "Talk To Me In Korean",
        duration: "3:56",
        sourceLang: "ko",
        targetLang: "vi",
        langLabel: "🇰🇷 한국어 → 🇻🇳 Tiếng Việt",
        summary: "Câu chuyện hài hước sử dụng từ vựng và đuôi câu sơ cấp, nói chậm rãi dễ hiểu.",
      },
      {
        level: 2,
        levelNumber: 2,
        badge: "TOPIK 2 • Cơ bản",
        difficulty: "Dễ",
        diffColor: "#06b6d4",
        id: "2NDS0F3bTwk",
        url: "https://www.youtube.com/watch?v=2NDS0F3bTwk",
        title: "Why Korean Cafes Are the Best – Văn hóa cà phê Hàn Quốc",
        author: "Cozy Storytime in Korean",
        duration: "4:52",
        sourceLang: "ko",
        targetLang: "vi",
        langLabel: "🇰🇷 한국어 → 🇻🇳 Tiếng Việt",
        summary: "Luyện nghe tự nhiên về sở thích đi quán cafe của giới trẻ Hàn Quốc.",
      },
      {
        level: 3,
        levelNumber: 3,
        badge: "TOPIK 3 • Trung cấp",
        difficulty: "Trung bình",
        diffColor: "#f59e0b",
        id: "mOry_eE_OZA",
        url: "https://www.youtube.com/watch?v=mOry_eE_OZA",
        title: "하필 소개팅 날에 – Buổi xem mắt dở khóc dở cười",
        author: "Korean Short Story B1",
        duration: "8:10",
        sourceLang: "ko",
        targetLang: "vi",
        langLabel: "🇰🇷 한국어 → 🇻🇳 Tiếng Việt",
        summary: "Mẩu chuyện tình huống xem mắt đầy tình tiết bất ngờ, giàu khẩu ngữ hàng ngày.",
      },
      {
        level: 4,
        levelNumber: 4,
        badge: "TOPIK 4 • Phỏng vấn",
        difficulty: "Khá khó",
        diffColor: "#f97316",
        id: "GbmWrEtC9h4",
        url: "https://www.youtube.com/watch?v=GbmWrEtC9h4",
        title: "How to Prepare Your Korean Job Interview? – Phỏng vấn việc làm",
        author: "MOFA Korea",
        duration: "3:14",
        sourceLang: "ko",
        targetLang: "vi",
        langLabel: "🇰🇷 한국어 → 🇻🇳 Tiếng Việt",
        summary: "Bộ Ngoại giao Hàn Quốc hướng dẫn trả lời phỏng vấn trang trọng và tự tin.",
      },
      {
        level: 5,
        levelNumber: 5,
        badge: "TOPIK 5-6 • Thời sự",
        difficulty: "Khó",
        diffColor: "#ef4444",
        id: "WY53J2YgqSI",
        url: "https://www.youtube.com/watch?v=WY53J2YgqSI",
        title: "Bản tin thời sự thời tiết YTN – Luyện nghe tốc độ MC",
        author: "YTN News",
        duration: "1:35",
        sourceLang: "ko",
        targetLang: "vi",
        langLabel: "🇰🇷 한국어 → 🇻🇳 Tiếng Việt",
        summary: "Bản tin thời sự đài truyền hình YTN Hàn Quốc có phụ đề chuẩn, ngữ điệu MC chuyên nghiệp.",
      },
    ],
  },
};

// Flat array for backward compatibility with existing code
export const PRESET_CARDS = [
  ...PRESET_LESSONS_BY_CATEGORY.en_general.lessons,
  ...PRESET_LESSONS_BY_CATEGORY.zh.lessons.slice(0, 1),
  ...PRESET_LESSONS_BY_CATEGORY.ja.lessons.slice(0, 1),
  ...PRESET_LESSONS_BY_CATEGORY.ko.lessons.slice(0, 1),
];
