export const PRESET_CARDS = [
  {
    id: "en-vi",
    url: "https://www.youtube.com/watch?v=9AVwbe4e6tI",
    sourceLang: "en",
    targetLang: "vi",
    icon: "🇺🇸",
    title: "Yunjin (LE SSERAFIM) – Interview",
    langLabel: "🇺🇸 English → 🇻🇳 Tiếng Việt",
    meta: "Variety Up Next • A2–B1 • Ngắn",
  },
  {
    id: "en-ko",
    url: "https://www.youtube.com/watch?v=h6fcK_fRYaI",
    sourceLang: "en",
    targetLang: "ko",
    icon: "🇺🇸",
    title: "The Egg – A Short Story",
    langLabel: "🇺🇸 English → 🇰🇷 한국어",
    meta: "Kurzgesagt • B2 • ~5 phút",
  },
  {
    id: "en-ja",
    url: "https://www.youtube.com/watch?v=UF8uR6Z6KLc",
    sourceLang: "en",
    targetLang: "ja",
    icon: "🇺🇸",
    title: "Steve Jobs Stanford Speech",
    langLabel: "🇺🇸 English → 🇯🇵 日本語",
    meta: "Stanford • C1 • ~15 phút",
  },
  {
    id: "ko-vi",
    url: "https://www.youtube.com/watch?v=GbmWrEtC9h4",
    sourceLang: "ko",
    targetLang: "vi",
    icon: "🇰🇷",
    title: "외교부 2019 총정리",
    langLabel: "🇰🇷 한국어 → 🇻🇳 Tiếng Việt",
    meta: "MOFA Korea • B1–B2 • 3:14",
  },
  {
    id: "ja-vi",
    url: "https://www.youtube.com/watch?v=_Z7j3PEU358",
    sourceLang: "ja",
    targetLang: "vi",
    icon: "🇯🇵",
    title: "We're Dreaming in TOKYO",
    langLabel: "🇯🇵 日本語 → 🇻🇳 Tiếng Việt",
    meta: "Tokyo Metropolitan Gov • B1 • 4:11",
  },
  {
    id: "zh-vi",
    url: "https://www.youtube.com/watch?v=97NV2txklwk",
    sourceLang: "zh",
    targetLang: "vi",
    icon: "🇨🇳",
    title: "Mandarin from the Streets",
    langLabel: "🇨🇳 中文 → 🇻🇳 Tiếng Việt",
    meta: "Better in Chinese • B1–B2",
  },
];
